name: Run PHPUnit tests

on:
  pull_request:
    branches:
      - main  # ou "master" selon ton projet

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl, yaml
          coverage: none

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Run PHPUnit
        run: ./vendor/bin/phpunit --configuration phpunit.xml.dist
